name: Trivy Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    name: Run Trivy Scan
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Run Trivy to scan for vulnerabilities in code (configuration scan)
      - name: Run Trivy Scanner for Config Files
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: config
          hide-progress: true
          output: trivy-config-results.txt

      # Run Trivy to scan the codebase for dependencies (vulnerability scan)
      - name: Run Trivy Scanner for Vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          hide-progress: true
          output: trivy-vulnerability-results.txt

      # Publish Trivy Output to GitHub Actions Summary
      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy-config-results.txt ]]; then
            {
              echo "### Configuration Scan Results"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```'
              cat trivy-config-results.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi

          if [[ -s trivy-vulnerability-results.txt ]]; then
            {
              echo "### Vulnerability Scan Results"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```'
              cat trivy-vulnerability-results.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi
          
      - name: List Files for Debugging
        run: ls -R

      - name: Move Trivy Results
        run: mkdir -p khushig3/Artifacts_Result && mv trivy-config-results.txt khushig3/Artifacts_Result/

      # Upload Trivy Results as Artifacts
      - name: Upload Trivy Results as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results
          path: khushig3/Artifacts_Result/*
            trivy-config-results.txt
            trivy-vulnerability-results.txt
